// Generated by re/gen_fx_tables.py from the XDJ-RX3 v1.19 player (mixerengine::SoundColorFxDubecho). Do not edit.

// DUBECHO_LPF_COEF_L [b0, b1, b2, a1, a2]
export const LPF_L = new Float32Array([
  0.025176115, 0.05035223, 0.025176115, -1.5036954, 0.6043998,
]);

// DUBECHO_HPF_COEF_L
export const HPF_L = new Float32Array([
  0.9717936, -1.9435872, 0.9717936, -1.9427915, 0.94438297,
]);

// DUBECHO_LPF_COEF_R
export const LPF_R = new Float32Array([
  0.29954416, 0.5990883, 0.29954416, 0.1457298, 0.05244679,
]);

// DUBECHO_HPF_COEF_R
export const HPF_R = new Float32Array([
  0.7770238, -1.5540476, 0.7770238, -1.5036954, 0.6043998,
]);
