// Generated by re/gen_fx_tables.py from the XDJ-RX3 v1.19 player (mixerengine::SoundColorFxSpace). Do not edit.

// m_leftside_lpf_coef [b0, b1, b2, a1, a2]
export const LEFT_LPF = new Float32Array([
  0.0046039983, 0.009207997, 0.0046039983, -1.7990965, 0.8175124,
]);

// m_leftside_hpf_coef
export const LEFT_HPF = new Float32Array([
  0.9800525, -1.960105, 0.9800525, -1.959707, 0.9605029,
]);

// m_rightside_lpf_coef
export const RIGHT_LPF = new Float32Array([
  0.14349347, 0.28698695, 0.14349347, -0.6807407, 0.25471458,
]);

// m_rightside_hpf_coef
export const RIGHT_HPF = new Float32Array([
  0.7385387, -1.4770774, 0.7385387, -1.4075054, 0.5466495,
]);
