// Generated by re/gen_fx_tables.py from the XDJ-RX3 v1.19 player (mixerengine::SoundColorFxSweep). Do not edit.

// GATE_LPF_COEF: the detector's low band (and the gate's post filter) [b0, b1, b2, a1, a2]
export const GATE_LPF = new Float32Array([
  0.00039787972, 0.00079575944, 0.00039787972, -1.9427915, 0.94438297,
]);

// GATE_HPF_COEF: the detector's high band
export const GATE_HPF = new Float32Array([
  0.9717936, -1.9435872, 0.9717936, -1.9427915, 0.94438297,
]);

// SWEEP_LPF_MAX_COEF: the sweep's low-passes at rest
export const SWEEP_LPF_MAX = new Float32Array([
  0.45568478, 0.91136956, 0.45568478, 0.46240512, 0.36033404,
]);

// SWEEP_HPF_MIN_COEF: the sweep's high-passes at rest
export const SWEEP_HPF_MIN = new Float32Array([
  0.99857527, -1.9971505, 0.99857527, -1.9971465, 0.99715453,
]);
